version: 2
updates:
  - package-ecosystem: gomod
    directory: /
    schedule:
      interval: monthly
      time: "09:00"
      timezone: Europe/Copenhagen
    open-pull-requests-limit: 5
    groups:
      go-dependencies:
        patterns:
          - "*"

  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: monthly
      time: "09:00"
      timezone: Europe/Copenhagen
    open-pull-requests-limit: 5
